title: H.Koh
position: PhD student
affiliation: University of Wisconsin-Madison
email: h.koh (at) wisc.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/MaximHelio
linkedin: https://www.linkedin.com/in/haejung-koh/
avatar: ./assets/img/tkn.jpeg
favicon: ./assets/img/tkn.jpeg
favicon_dark: ./assets/img/tkn.jpeg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://github.com/MaximHelio
remote_theme: yaoyao-liu/minimal-light
facebook: https://www.facebook.com/profile.php?id=61578223883768
