title: Nam D. Nguyen
position: Ph.D. Candidate in Computer Science
affiliation: Stony Brook University
email: ndnguyen (at) cs.stonybrook.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=-rBLWMAAAAAJ&hl=en
github_link: https://github.com/namtk
linkedin: https://www.linkedin.com/in/namtrk/
avatar: ./assets/img/tkn.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/tkn.jpeg
favicon_dark: ./assets/img/tkn.jpeg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://namtk.github.io/
remote_theme: yaoyao-liu/minimal-light
facebook: https://www.facebook.com/namtk
